const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');
const { db, pool } = require('../backend/config/database');

dotenv.config();

async function cleanupTestCourses() {
  try {
    // Only delete automated test courses generated by smoke tests
    const [testCourses] = await pool.query(`
      SELECT id, course_name, course_code
      FROM courses
      WHERE course_code LIKE 'AUTO_CRS_%'
         OR course_code LIKE 'EXP_CRS_%'
         OR course_code LIKE 'SEC_%'
    `);

    for (const course of testCourses) {
      await pool.query(
        'DELETE FROM exam_answers WHERE exam_attempt_id IN (SELECT id FROM exam_attempts WHERE course_id = ?)',
        [course.id]
      );
      await pool.query('DELETE FROM exam_attempts WHERE course_id = ?', [course.id]);
      await pool.query('DELETE FROM questions WHERE course_id = ?', [course.id]);
      await pool.query('DELETE FROM courses WHERE id = ?', [course.id]);
      console.log(`Cleaned up test subject: ${course.course_code} (${course.course_name})`);
    }
  } catch (err) {
    console.warn('Subject cleanup notice:', err.message);
  }
}

async function cleanupOrphanedSmokeUsers() {
  try {
    // Retain only 1 smoke test user, delete all other accumulated smoke test accounts
    await pool.query(`
      DELETE FROM exam_answers WHERE exam_attempt_id IN (
        SELECT id FROM exam_attempts WHERE user_id IN (
          SELECT id FROM users WHERE email LIKE 'smoke_%' AND email != 'smoke_test_user@medprep.com'
        )
      )
    `);
    await pool.query(`
      DELETE FROM exam_attempts WHERE user_id IN (
        SELECT id FROM users WHERE email LIKE 'smoke_%' AND email != 'smoke_test_user@medprep.com'
      )
    `);
    await pool.query(`
      DELETE FROM users WHERE email LIKE 'smoke_%' AND email != 'smoke_test_user@medprep.com'
    `);
  } catch (err) {
    // Ignore cleanup warnings
  }
}

async function migrateCoursesTable() {
  try {
    const [schemaRows] = await pool.query(
      "SELECT sql FROM sqlite_master WHERE type='table' AND name='courses'"
    );
    const currentSql = schemaRows[0]?.sql || '';
    if (currentSql.includes('course_code TEXT NOT NULL UNIQUE')) {
      console.log('Migrating courses table to support per-user course code isolation...');
      await pool.query('PRAGMA foreign_keys = OFF');
      await pool.query(`
        CREATE TABLE IF NOT EXISTS courses_new (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          course_name TEXT NOT NULL,
          course_code TEXT NOT NULL,
          course_description TEXT,
          created_by INTEGER NULL,
          created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
          updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
          UNIQUE(course_code, created_by)
        )
      `);
      await pool.query(
        'INSERT INTO courses_new (id, course_name, course_code, course_description, created_by, created_at, updated_at) ' +
        'SELECT id, course_name, course_code, course_description, created_by, created_at, updated_at FROM courses'
      );
      await pool.query('DROP TABLE courses');
      await pool.query('ALTER TABLE courses_new RENAME TO courses');
      await pool.query('CREATE INDEX IF NOT EXISTS idx_courses_name ON courses(course_name)');
      await pool.query('CREATE INDEX IF NOT EXISTS idx_courses_code ON courses(course_code)');
      await pool.query('PRAGMA foreign_keys = ON');
      console.log('Courses table migration completed successfully.');
    }
  } catch (err) {
    console.warn('Courses migration notice:', err.message);
  }
}

async function initDatabase() {
  try {
    // 1. Check if tables already exist (e.g. uploaded SQLite file in Turso)
    const [existing] = await pool.query(
      "SELECT name FROM sqlite_master WHERE type='table' AND name='users'"
    );

    if (existing && existing.length > 0) {
      console.log('Database tables verified in Turso (libSQL).');
      await cleanupOrphanedSmokeUsers();
      await migrateCoursesTable();
      return true;
    }

    // 2. If not yet initialized, read and execute schema statements individually
    const schemaPath = path.join(__dirname, 'schema.sql');
    const schemaSql = fs.readFileSync(schemaPath, 'utf8');

    const cleanSql = schemaSql.replace(/--.*$/gm, '');
    const statements = cleanSql
      .split(';')
      .map((s) => s.trim())
      .filter((s) => s.length > 0 && !s.toLowerCase().startsWith('pragma journal_mode'));

    for (const statement of statements) {
      try {
        await pool.query(statement);
      } catch (stmtErr) {
        if (!stmtErr.message.includes('already exists')) {
          console.warn('Schema statement warning:', stmtErr.message);
        }
      }
    }

    await cleanupOrphanedSmokeUsers();
    await migrateCoursesTable();
    console.log('Database and tables initialized successfully with Turso (libSQL).');
    return true;
  } catch (error) {
    console.error('Database initialization notice:', error.message);
    try {
      const [check] = await pool.query('SELECT COUNT(*) as count FROM users');
      if (check && check.length > 0) {
        console.log('Existing database verified functional.');
        return true;
      }
    } catch (_) {}
    throw error;
  }
}

if (require.main === module) {
  initDatabase().then(() => {
    process.exit(0);
  }).catch((error) => {
    console.error(error);
    process.exit(1);
  });
}

module.exports = {
  initDatabase,
  cleanupTestCourses,
  cleanupSingleQuestionCourses: cleanupTestCourses,
  cleanupOrphanedSmokeUsers,
};
